providers = ["node"]

[phases.install]
cmds = [
  "rm -f package-lock.json",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node --max-old-space-size=4096 server.cjs"

